"""Azure provider connection settings: SQL, Search, OpenAI, App Insights."""
import os

from infrastructure.azure.keyvault import get_secret

# ── Azure SQL ──
ENVIRONMENT_FOR_SQL = os.getenv("ENVIRONMENT_SET_FOR_SQL")
if ENVIRONMENT_FOR_SQL == "LOCAL":
    MSSQL_CONNECTION_STRING = os.getenv("MSSQL_CONNECTION_STRING")
else:
    MSSQL_CONNECTION_STRING = get_secret("MSSQL-CONNECTION-STRING")
AZURE_SQL_CHECKPOINT_TABLE = os.getenv("AZURE_SQL_CHECKPOINT_TABLE", "langgraph_checkpoints")
AZURE_SQL_USE_MANAGED_IDENTITY = os.getenv("AZURE_SQL_USE_MANAGED_IDENTITY", "false").lower() == "true"
AZURE_SQL_SERVER = get_secret("AZURE-SQL-SERVER")
AZURE_SQL_DATABASE = get_secret("AZURE-SQL-DATABASE")
AZURE_SQL_DRIVER = os.getenv("AZURE_SQL_DRIVER", "ODBC Driver 18 for SQL Server")
AZURE_SQL_MANAGED_IDENTITY_CLIENT_ID = get_secret("AZURE-SQL-MANAGED-IDENTITY-CLIENT-ID")

# ── Azure Search ──
AZURE_SEARCH_SERVICE = get_secret("AZURE-SEARCH-SERVICE")
AZURE_SEARCH_INDEX = get_secret("AZURE-SEARCH-INDEX")
AZURE_SEARCH_KEY = get_secret("AZURE-SEARCH-KEY")
AZURE_SEARCH_ENDPOINT = get_secret("AZURE-SEARCH-ENDPOINT")
AZURE_SEARCH_API_KEY = get_secret("AZURE-SEARCH-API-KEY")
AZURE_SEARCH_INDEX_NAME = get_secret("AZURE-SEARCH-INDEX-NAME")
AZURE_SEARCH_VECTOR_FIELD = os.getenv("AZURE_SEARCH_VECTOR_FIELD", "content_vector")
AZURE_SEARCH_VECTOR_COLUMNS = os.getenv("AZURE_SEARCH_VECTOR_COLUMNS", "content_vector")
AZURE_SEARCH_CONTENT_COLUMNS = os.getenv("AZURE_SEARCH_CONTENT_COLUMNS", "content")
AZURE_SEARCH_API_VERSION = get_secret("AZURE-SEARCH-API-VERSION", "2023-11-01")
AZURE_SEARCH_SEMANTIC_CONFIG = get_secret("AZURE-SEARCH-SEMANTIC-CONFIG", "")

# ── Azure OpenAI ──
AZURE_OPENAI_ENDPOINT = get_secret("AZURE-OPENAI-ENDPOINT")
AZURE_OPENAI_KEY = get_secret("AZURE-OPENAI-KEY")
AZURE_OPENAI_CHAT_DEPLOYMENT = get_secret("AZURE-OPENAI-CHAT-DEPLOYMENT")
# Note: AZURE_OPENAI_CHAT_API_VERSION is bound twice in legacy config — KV first,
# then env-var override. We preserve the env-var (final) value here.
AZURE_OPENAI_CHAT_API_VERSION = os.getenv("AZURE_OPENAI_CHAT_API_VERSION", "2024-10-21")
AZURE_OPENAI_EMBED_ENDPOINT = get_secret("AZURE-OPENAI-EMBED-ENDPOINT") or AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_EMBED_API_KEY = get_secret("AZURE-OPENAI-EMBED-API-KEY") or AZURE_OPENAI_KEY
AZURE_OPENAI_API_VERSION = get_secret("AZURE-OPENAI-EMBED-API-VERSION", "2024-02-01")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT = get_secret("AZURE-OPENAI-EMBEDDING-DEPLOYMENT")
AZURE_OPENAI_EMBEDDING_DIMENSIONS = int(get_secret("AZURE-OPENAI-EMBEDDING-DIMENSIONS", "3072"))

# ── Application Insights ──
APPLICATIONINSIGHTS_CONNECTION_STRING = get_secret("APPLICATIONINSIGHTS-CONNECTION-STRING")
