"""
LangGraph state definition.
This TypedDict flows through every node in the RAG StateGraph.

Uses LangGraph's ``messages`` pattern with ``add_messages`` reducer
so that conversation history is managed automatically by the
checkpoint system.
"""
from typing import Annotated, TypedDict
from langgraph.graph.message import add_messages, BaseMessage


class RAGState(TypedDict, total=False):
    # ── LangGraph managed conversation messages ──
    # Automatically accumulated by add_messages reducer across checkpoints.
    messages: Annotated[list[BaseMessage], add_messages]

    # ── Conversation summary (for token-efficient memory) ──
    summary: str

    # ── Input (from client request) ──
    input_type: str
    user_input: str
    is_free_form: bool
    user_id: str
    chat_id: str | None
    chat_session_id: str | None   # LangGraph thread key — must round-trip to SQL for edit/regen
    message_id: str | None
    channel_type: int
    function: list[str]
    sub_function: list[str]
    source_url: list[str]
    start_date: str
    end_date: str
    preferred_language: str | None
    content_type: str  # "document" (default) | "qa_pair" — search index content_type filter

    # ── RBAC / Rank personalisation ──
    # rank_code & rank_name come directly from the (now mandatory) request fields.
    # rank_info is the canonical dict resolved via core.rbac.resolve_rank_strict —
    # used by the generate node to personalise the system prompt and by the
    # supervisor's _get_next to gate access to non-RAG agents.
    rank_code: int | None
    rank_name: str | None
    rank_info: dict | None

    # ── Document → QA fallback (graph-level retry) ──
    needs_doc_fallback: bool       # trigger retry with qa_pair after no-answer generation
    doc_fallback_attempted: bool   # prevent infinite fallback loop

    # ── Function gate (selection enforcement before search) ──
    requires_function_selection: bool
    function_required_reason: str | None  # message shown to user when re-selection is required
    function_hint: str | None  # non-blocking hint suggesting user select a function

    # ── Validation ──
    is_greeting: bool
    validation_error: str | None

    # ── Query processing ──
    rewritten_query: dict | None   # {"query": str, "filter": str | None}
    functions_found: list[str]
    is_ambiguous: bool
    pending_ambiguous_query: dict | None  # Original query context saved during ambiguity
    needs_multi_search: bool  # True when search found multiple functions, triggers iterative search
    multi_search_status: list[str]  # Status messages from iterative multi-function search (streamed via updates mode)

    # ── Search results ──
    events: list

    # ── Generation ──
    ai_content: str | None
    prompt_used: str | None

    # ── Long-term memory (from LangGraph Store — cross-session) ──
    user_memories: list[str]
    current_context: str  # Track conversation context (applying, checking, asking)
    next: str

    # ── Suggestive actions (generated by Supervisor, returned in final SSE event) ──
    # Each item: {"short_title": str, "description": str}
    suggestive_actions: list | None

    # ── Conversation title (auto-generated from first exchange) ──
    conversation_title: str | None

    # ── Multi-turn citation tracking ──
    # Maps citation number → {url, content_snippet} so follow-up questions
    # can resolve "tell me more about [2]" to the original source.
    citation_map: dict | None

    # ── Output ──
    response: dict | None
    error_info: dict | None

    # ── Multi-step agent (parallel search — Phase 2) ──
    plan_type: str | None          # "simple" | "complex"
    sub_queries: list | None       # [{"function": str, "query": str}] from planner
    parallel_results: list | None  # [{"function": str, "events": list}] from parallel search

    # ── Multi-agent orchestration (LMS / Expense / Scorecard) ──
    # All fields are optional; absence means "this agent did not run".
    # Each agent stores its raw tool result here for the format node and
    # for downstream observability. The shape is agent-specific dict.
    lms_result: dict | None
    lms_sub_intent: str | None     # "balance" | "applications" | "approvals" | "unknown"

    # ── Expense & Scorecard (predicate-planner agents) ──
    # User's GUI (Employee ID); from frontend, mandatory.
    # Drives row-level security: non-admin ranks see only their own GUI.
    gui: str | None

    # Each agent stashes its compiled SQL, params, rowcount + raw rows for
    # the format node + audit telemetry.
    expense_result: dict | None
    expense_plan: dict | None       # serialised QueryPlan
    scorecard_result: dict | None
    scorecard_plan: dict | None     # serialised QueryPlan

    # ── RBAC denial UX ──
    # Set by supervisor._get_next when a route is gated and falls back to
    # RESPOND, so the next supervisor turn can compose a polite denial.
    access_denied_reason: str | None
